# nano /var/lib/vz/snippets/user-data.yaml
#cloud-config
hostname: cbresponse
fqdn: cbresponse.local
manage_etc_hosts: true

users:
  - name: root
    plain_text_passwd: "Wicked1!"
    lock_passwd: false
    shell: /bin/bash

  - name: centos
    plain_text_passwd: "WWicked1!"
    lock_passwd: false
    shell: /bin/bash
    groups: wheel
    sudo: ALL=(ALL) NOPASSWD:ALL

ssh_pwauth: true
disable_root: false

timezone: Australia/Sydney
package_update: true
packages:
  - qemu-guest-agent

write_files:
  - path: /etc/ssh/sshd_config.d/99-rootlogin.conf
    content: |
      PermitRootLogin yes
      PasswordAuthentication yes

runcmd:
  - systemctl enable --now qemu-guest-agent
  - systemctl restart sshd
  - sysctl -w net.ipv6.conf.all.disable_ipv6=1
  - sysctl -w net.ipv6.conf.default.disable_ipv6=1
  - echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
  - echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.conf
